### ISSUE TITLE
django.db.utils.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]数据类型 nvarchar 和 ntext 在 equal to 运算符中不兼容。 (402) (SQLExecDirectW); [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]无法预定义语句。 (8180)')

### ISSUE THREAD

**Issue by bcahlit** [michiya/django-pyodbc-azure#123]
Django==1.11.7
pyodbc==4.0.21
django-pyodbc==1.1.1
django-pyodbc-azure==1.11.0.0
Microsoft sql Server == 2008

I am trying to use sql server in Django According to Django's tutorial, I created a data model. These errors were encountered while syncing. I tried to search some communities and found no solution available.

It has a part of the Chinese translation should be like this:

Data Type nvarchar and ntext are not compatible with equal to operator. (402) (SQLExecDirectW); [42000] [42000] [42000] [ODBC] [Microsoft] [ODBC SQL Server Driver] [SQL Server] Unable to predefine. (8180) ')

This is my error message.
`
D:\django\mysite>python manage.py makemigrations polls
Migrations for 'polls':
  polls\migrations\0001_initial.py
    - Create model Choice
    - Create model Question
    - Add field question to choice

D:\django\mysite>python manage.py sqlmigrate polls 0001
BEGIN TRANSACTION
--
-- Create model Choice
--
CREATE TABLE [polls_choice] ([id] int IDENTITY (1, 1) NOT NULL PRIMARY KEY, [choice_text] nvarchar(200) NOT NULL, [votes] int NOT NULL);
--
-- Create model Question
--
CREATE TABLE [polls_question] ([id] int IDENTITY (1, 1) NOT NULL PRIMARY KEY, [question_text] nvarchar(200) NOT NULL, [pub_date] datetime NOT NULL);
--
-- Add field question to choice
--
ALTER TABLE [polls_choice] ADD [question_id] int NOT NULL;
CREATE INDEX [polls_choice_question_id_c5b4b260] ON [polls_choice] ([question_id]);
ALTER TABLE [polls_choice] ADD CONSTRAINT [polls_choice_question_id_c5b4b260_fk_polls_question_id] FOREIGN KEY ([question_id]) REFERENCES [polls_question] ([id]);
COMMIT;

D:\django\mysite>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, polls, sessions
Running migrations:
  Applying contenttypes.0002_remove_content_type_name...Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\sql_server\pyodbc\base.py", line 545, in execute
    return self.cursor.execute(sql, params)
pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]数据类型 nvarchar and ntext 在 equal to 运算符中不兼容。 (402) (SQLExecDirectW); [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]无法预定义语句。 (8180)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\commands\migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\migrations\executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\migrations\executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\migrations\executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\migrations\migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\migrations\operations\fields.py", line 155, in database_forwards
    schema_editor.remove_field(from_model, from_model._meta.get_field(self.name))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\sql_server\pyodbc\schema.py", line 655, in remove_field
    constraints = self.connection.introspection.get_constraints(cursor, model._meta.db_table)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\sql_server\pyodbc\introspection.py", line 278, in get_constraints
    """, [table_name])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\backends\utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\sql_server\pyodbc\base.py", line 545, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]数据类型 nvarchar 和 ntext 在 equal to 运算符中不兼容。 (402) (SQLExecDirectW); [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]无法预定义语句。 (8180)')
`

**Comment by bcahlit** [comment]
this is my data model。
# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, max_length=255)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

**Comment by michiya** [comment]
The issue seems to be the same as #111. Try Microsoft ODBC Driver for SQL Server.

**Comment by michiya** [comment]
Closing due to inactivity.

**Comment by alexpt10** [comment]
Se debe cambiar en la base de datos el tipo de campo, debe quedar [varchar](max).

si ya existe se debe cambiar de la siguiente manera 

ALTER TABLE [dbo].[Aplicaciones] 
ALTER COLUMN  [Direccion] [varchar](max)

Ojo: Para Sql Server.

**Comment by alexpt10** [comment]
ALTER TABLE [dbo].[Aplicaciones] 
ALTER COLUMN  [Direccion] [varchar](max)
