### ISSUE TITLE
Why has support for the newest LTS version of Django been removed?

### ISSUE THREAD

**Issue by beruic** [michiya/django-pyodbc-azure#139]
I am using Django 1.11.10 because it is the newest LTS version, but this seam to mean that I cannot use `django-pyodbc-azure`.

Why is the newest LTS version of Django not supported?

**Comment by beruic** [comment]
I have been poking around with this, and gotten to this:

On Django 1.11.10 the `load_backend` function in gives an exception on `return import_module('%s.base' % backend_name)`. In Django 2.0.2 it doesn't.

I can find no difference between the two versions in the code that leads up to that point.

The exception that it thrown under Django 1.11.10:
```
Traceback (most recent call last):
  File "/home/jk/.virtualenvs/my_project/lib/python3.5/site-packages/django/db/utils.py", line 115, in load_backend
    return import_module('%s.base' % backend_name)
  File "/home/jk/.virtualenvs/my_project/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/jk/.virtualenvs/my_project/lib/python3.5/site-packages/sql_server/pyodbc/base.py", line 16, in <module>
    from django.utils.version import get_version_tuple
ImportError: cannot import name 'get_version_tuple'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/pycharm-professional/47/helpers/pydev/pydevd.py", line 1668, in <module>
    main()
  File "/snap/pycharm-professional/47/helpers/pydev/pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/snap/pycharm-professional/47/helpers/pydev/pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/47/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/jk/git/text-search-service/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/jk/.virtualenvs/my_project/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/jk/.virtualenvs/my_project/lib/python3.5/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/jk/.virtualenvs/my_project/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jk/.virtualenvs/my_project/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/home/jk/.virtualenvs/my_project/lib/python3.5/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/jk/.virtualenvs/my_project/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/jk/.virtualenvs/my_project/lib/python3.5/site-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/home/jk/.virtualenvs/my_project/lib/python3.5/site-packages/django/contrib/auth/base_user.py", line 52, in <module>
    class AbstractBaseUser(models.Model):
  File "/home/jk/.virtualenvs/my_project/lib/python3.5/site-packages/django/db/models/base.py", line 124, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/home/jk/.virtualenvs/my_project/lib/python3.5/site-packages/django/db/models/base.py", line 325, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/jk/.virtualenvs/my_project/lib/python3.5/site-packages/django/db/models/options.py", line 214, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/home/jk/.virtualenvs/my_project/lib/python3.5/site-packages/django/db/__init__.py", line 33, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/home/jk/.virtualenvs/my_project/lib/python3.5/site-packages/django/db/utils.py", line 211, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/home/jk/.virtualenvs/my_project/lib/python3.5/site-packages/django/db/utils.py", line 134, in load_backend
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: 'sql_server.pyodbc' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'
Error was: cannot import name 'get_version_tuple'
```

**Comment by beruic** [comment]
I should mention that to get this far, I have disabled the version check of `django-pyodbc-azure`, so therefore the import of `get_version_tuple` naturally fails, at it is not in Django 1.11.

**Comment by michiya** [comment]
django-pyodbc-azure for Django-1.11 is available on PyPI even now.
https://pypi.python.org/pypi/django-pyodbc-azure/1.11.9.0

You can use pip to install it (`pip install "django-pyodbc-azure<2.0"`) or download it from the PyPI page above.

**Comment by beruic** [comment]
Oh! Thank you so much!!!
I didn't realize that there was another version for that. Perhaps time for an update of the README?

**Comment by beruic** [comment]
@michiya is the default driver different between the versions? I have Micosoft ODBC Driver for SQL Server installed, but now it looks for FreeTDS instead.

**Comment by beruic** [comment]
That was it. Should I create a pull request to change the default for Django 1.11?
The Micosoft ODBC Driver for SQL Server is pretty easy to install on Ubuntu at least. It didn't work for me out of the box with FreeTDS, however.

**Comment by michiya** [comment]
Thanks but you don't need to make a PR for it because it is intentional. There might be Django 1.11 users who are using FreeTDS without specifying explicit driver option. I don't want to bring a breaking change to them.
