### ISSUE TITLE
The database driver doesn't support modern datatime types

### ISSUE THREAD

**Issue by Sirichakorn** [michiya/django-pyodbc-azure#161]
I'm use python 3.4.3, django 2.0.4, FreeTDS v1.1.dev.20180427 on Ubuntu 14.04
connect to MSSQL 2017.
when I run "python manage.py migrate" I got error message below.

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dev/envdjango2/lib/python3.4/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/dev/envdjango2/lib/python3.4/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dev/envdjango2/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/dev/envdjango2/lib/python3.4/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/dev/envdjango2/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 79, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/dev/envdjango2/lib/python3.4/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/dev/envdjango2/lib/python3.4/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/dev/envdjango2/lib/python3.4/site-packages/django/db/migrations/loader.py", line 206, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/dev/envdjango2/lib/python3.4/site-packages/django/db/migrations/recorder.py", line 61, in applied_migrations
    if self.has_table():
  File "/home/dev/envdjango2/lib/python3.4/site-packages/django/db/migrations/recorder.py", line 44, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/home/dev/envdjango2/lib/python3.4/site-packages/django/db/backends/base/base.py", line 255, in cursor
    return self._cursor()
  File "/home/dev/envdjango2/lib/python3.4/site-packages/django/db/backends/base/base.py", line 232, in _cursor
    self.ensure_connection()
  File "/home/dev/envdjango2/lib/python3.4/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/home/dev/envdjango2/lib/python3.4/site-packages/django/db/backends/base/base.py", line 196, in connect
    self.init_connection_state()
  File "/home/dev/envdjango2/lib/python3.4/site-packages/sql_server/pyodbc/base.py", line 365, in init_connection_state
    "The database driver doesn't support modern datatime types.")
django.core.exceptions.ImproperlyConfigured: The database driver doesn't support modern datatime types.
```

I try to fix this error for a few days but not success. Anyone know how to fix it.
Thank in advance.

**Comment by shaib** [comment]
Your versions of Django (and supposedly django-pyodbc-azure) and FreeTDS look quite recent, so I'd look at upgrading pyodbc and perhaps the system ODBC libraries and utilities (libodbc, unixodbc, odbcinst are the first to come to mind).

**Comment by Sirichakorn** [comment]
I already used newest version of pyodbc and unixodbc (pyodbc 4.0.23, unixodbc 2.2.14p2-5ubuntu5).

**Comment by michiya** [comment]
You may be able to resolve the issue by setting `tds version` to 7.3 or above in your freetds.conf. See #142 for more details.

**Comment by Sirichakorn** [comment]
Ok. I solved it.
    Cause is I have 2 TDS's package is duplicate (tdsodbc & FreeTDS) and my unixODBC use tdsodbc which TDS_Version=4.2 but I understand my unixODBC use FreeTDS which TDS_Version=7.4  ha ha...
    Solve is remove tdsodbc, set driver of unixODBC as FreeTDS and use TDS_Version=7.4 (FreeTDS v.1.1 must build from git because if use apt-get have just v.0.91)

Thank for your time.
