### ISSUE TITLE
Django 1.8 compatibilty

### ISSUE THREAD

**Issue by MarcoPassanisi** [michiya/django-pyodbc-azure#22]
i try to use with django 1.8 alpha but i recived this error when run /manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fef24903c80>
Traceback (most recent call last):
  File "/home/marco/env/lib/python3.4/site-packages/django/db/utils.py", line 109, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib/python3.4/importlib/**init**.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/marco/env/lib/python3.4/site-packages/sql_server/pyodbc/base.py", line 40, in <module>
    from sql_server.pyodbc.operations import DatabaseOperations
  File "/home/marco/env/lib/python3.4/site-packages/sql_server/pyodbc/operations.py", line 5, in <module>
    from django.db.backends import BaseDatabaseOperations
ImportError: cannot import name 'BaseDatabaseOperations'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marco/env/lib/python3.4/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(_args, *_kwargs)
  File "/home/marco/env/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 111, in inner_ru
n
    self.validate(display_num_errors=True)
  File "/home/marco/env/lib/python3.4/site-packages/django/core/management/base.py", line 465, in validate
    return self.check(app_configs=app_configs, display_num_errors=display_num_errors)
  File "/home/marco/env/lib/python3.4/site-packages/django/core/management/base.py", line 478, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/marco/env/lib/python3.4/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/marco/env/lib/python3.4/site-packages/django/core/checks/model_checks.py", line 28, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/home/marco/env/lib/python3.4/site-packages/django/db/models/base.py", line 1166, in check
    errors.extend(cls._check_long_column_names())
  File "/home/marco/env/lib/python3.4/site-packages/django/db/models/base.py", line 1567, in _check_long_column_names
    connection = connections[db]
  File "/home/marco/env/lib/python3.4/site-packages/django/db/utils.py", line 238, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/home/marco/env/lib/python3.4/site-packages/django/db/utils.py", line 127, in load_backend
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: 'sql_server.pyodbc' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'base', 'mysql', 'oracle', 'postgresql_psycopg2', 'sqlite3'
Error was: cannot import name 'BaseDatabaseOperations'

**Comment by michiya** [comment]
Thank you for reporting. The backend doesn't support Django 1.8 because Django 1.8 is not in stable status yet. I hope I can make it compatible with Django 1.8 when the new Django gets ready for production use in the future.

**Comment by michiya** [comment]
The new version of the backend that supports Django 1.8 is now available on PyPI. Please submit a new issue if you have a problem with the new backend.

**Comment by Alexander-KI** [comment]
I have the same issue...
Running CentOS 7 + python 2.7 + Django 1.8 + pyodbc

**Comment by dhruv0706** [comment]
I have the same issue 
Running on windows 10 + python 3.5 + Django 1.8 + mysql 2.7
