### ISSUE TITLE
"Attempt to use a closed cursor" on migrate.

### ISSUE THREAD

**Issue by bsadecki** [michiya/django-pyodbc-azure#33]
I'm getting this error on migrate:

```
django.db.utils.ProgrammingError: Attempt to use a closed cursor.
```

Mac OS X
Django==1.8.2
django-pyodbc-azure==1.8.1.0
pyodbc==3.0.10
python 2.7

DB settings (censored, obv)

```
    'default': {
        'ENGINE': "sql_server.pyodbc",
        'HOST': "*****",
        'USER': "***\\****",
        'PASSWORD': "******",
        'NAME': "******",
        'OPTIONS': {
            'driver': 'FreeTDS',
        },
    },
```

These settings are correct; a migrations table is created.

Full Traceback:

```
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/django_user/.virtualenvs/django_environment/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/django_user/.virtualenvs/django_environment/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/django_user/.virtualenvs/django_environment/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/django_user/.virtualenvs/django_environment/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/Users/django_user/.virtualenvs/django_environment/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 179, in handle
    created_models = self.sync_apps(connection, executor.loader.unmigrated_apps)
  File "/Users/django_user/.virtualenvs/django_environment/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 317, in sync_apps
    cursor.execute(statement)
  File "/Users/django_user/.virtualenvs/django_environment/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/django_user/.virtualenvs/django_environment/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/django_user/.virtualenvs/django_environment/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/django_user/.virtualenvs/django_environment/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/Users/django_user/.virtualenvs/django_environment/lib/python2.7/site-packages/sql_server/pyodbc/base.py", line 474, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: Attempt to use a closed cursor.
```

**Comment by michiya** [comment]
@bsadecki Thank you for reporting, and it might be a bug in the backend.

Can I ask you something to make sure I understand you correctly:
- Running migration gives you the error without creating tables other than django_migrations, right?
- Which driver manager are you using on your OS X, unixODBC or iODBC?

**Comment by bsadecki** [comment]
> Running migration gives you the error without creating tables other than django_migrations, right?

That's right.

> Which driver manager are you using on your OS X, unixODBC or iODBC?

unixODBC, which I set up using these instructions: https://github.com/lionheart/django-pyodbc/wiki/Mac-setup-to-connect-to-a-MS-SQL-Server

Small update: I'm able to migrate individual apps and, after that, run a project-wide migrate. Maybe one of the apps I was using was blocking?

**Comment by michiya** [comment]
@bsadecki Thank you for the details. I'm not quite sure yet, but it might be caused by one of your applications. Could you give me the verbose messages and the error traceback running migrations with `--traceback` and `--verbosity=3` options?
