### ISSUE TITLE
'unicode' object has no attribute 'tzinfo'

### ISSUE THREAD

**Issue by alexsilva** [michiya/django-pyodbc-azure#58]
django=1.9.6
django-pyodbc-azure=1.9.3
python=2.7
OS Windows 64

It is occurring failure on the date of conversion that is not in datetime format when the conversion is necessary.

The date value is a string when it should be a datetime object.

[https://docs.djangoproject.com/en/1.9/ref/utils/#django.utils.timezone.make_aware](make_aware)

There is already a solution for this problem ?

```
Traceback (most recent call last):
  File "...\django\core\handlers\base.py", line 123, in get_response
    response = middleware_method(request)
  File "...\django\middleware\locale.py", line 25, in process_request
    request, check_path=self.is_language_prefix_patterns_used)
  File "...\django\utils\translation\__init__.py", line 199, in get_language_from_request
    return _trans.get_language_from_request(request, check_path)
  File "...\django\utils\translation\trans_real.py", line 494, in get_language_from_request
    lang_code = request.session.get(LANGUAGE_SESSION_KEY)
  File "...\django\contrib\sessions\backends\base.py", line 61, in get
    return self._session.get(key, default)
  File "...\django\contrib\sessions\backends\base.py", line 201, in _get_session
    self._session_cache = self.load()
  File "...\django\contrib\sessions\backends\db.py", line 33, in load
    expire_date__gt=timezone.now()
  File "...\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "...\django\db\models\query.py", line 381, in get
    num = len(clone)
  File "...\django\db\models\query.py", line 240, in __len__
    self._fetch_all()
  File "...\django\db\models\query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "...\django\db\models\query.py", line 68, in __iter__
    for row in compiler.results_iter(results):
  File "...\django\db\models\sql\compiler.py", line 808, in results_iter
    row = self.apply_converters(row, converters)
  File "...\django\db\models\sql\compiler.py", line 792, in apply_converters
    value = converter(value, expression, self.connection, self.query.context)
  File "...\sql_server\pyodbc\operations.py", line 108, in convert_datetimefield_value
    value = timezone.make_aware(value, timezone.utc)
  File "...\django\utils\timezone.py", line 364, in make_aware
    return timezone.localize(value, is_dst=is_dst)
  File "..env\lib\site-packages\pytz\__init__.py", line 225, in localize
    if dt.tzinfo is not None:
AttributeError: 'unicode' object has no attribute 'tzinfo'
```

**Comment by alexsilva** [comment]
The problem was being caused in an old database. When creating a new problem disappeared.

**Comment by unformatt** [comment]
Still a valid bug though since django-pyodbc-azure tries to detect old DB date types here: https://github.com/michiya/django-pyodbc-azure/blob/azure-1.9/sql_server/pyodbc/base.py#L364

But then here doesn't check and handle string date type:
https://github.com/michiya/django-pyodbc-azure/blob/azure-1.9/sql_server/pyodbc/operations.py#L103

**Comment by unformatt** [comment]
Another wrinkle, this only happens on Windows. Connecting to the same exact DB but from Mac, django-pyodbc-azure somehow gets the date as an object.
