### ISSUE TITLE
DateTime objects from MSSQL database are not considered as datetime, but as strings

### ISSUE THREAD

**Issue by pmahata** [michiya/django-pyodbc-azure#70]
**Platform details:** Django:1.9.9, pyodbc:: 3.0.10, django-pyodbc-azure:1.9.6.0 (Thanks for the package, saved me for connecting to MSSQL from Django on a windows platform).

**Use case:** I am simply using django admin and tried to edit a user in the admin view. The login time and date joined time are seen in \sql_server\pyodbc\operations.py", line 106, in convert_datetimefield_value are not properly converted as Djago datetime objects, I suppose. It throws an AttributeError at /admin/ with following info:

 **'str' object has no attribute 'tzinfo'**

**Trace**

Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "C:\Python34\lib\site-packages\django\contrib\admin\sites.py", line 265, in wrapper
    return self.admin_view(view, cacheable)(_args, *_kwargs)
  File "C:\Python34\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, _args, *_kwargs)
  File "C:\Python34\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, _args, *_kwargs)
  File "C:\Python34\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    if not self.has_permission(request):
  File "C:\Python34\lib\site-packages\django\contrib\admin\sites.py", line 173, in has_permission
    return request.user.is_active and request.user.is_staff
  File "C:\Python34\lib\site-packages\django\utils\functional.py", line 204, in inner
    self._setup()
  File "C:\Python34\lib\site-packages\django\utils\functional.py", line 351, in _setup
    self._wrapped = self._setupfunc()
  File "C:\Python34\lib\site-packages\django\contrib\auth\middleware.py", line 22, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "C:\Python34\lib\site-packages\django\contrib\auth\middleware.py", line 10, in get_user
    request._cached_user = auth.get_user(request)
  File "C:\Python34\lib\site-packages\django\contrib\auth__init__.py", line 174, in get_user
    user = backend.get_user(user_id)
  File "C:\Python34\lib\site-packages\django\contrib\auth\backends.py", line 93, in get_user
    return UserModel._default_manager.get(pk=user_id)
  File "C:\Python34\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(_args, *_kwargs)
  File "C:\Python34\lib\site-packages\django\db\models\query.py", line 381, in get
    num = len(clone)
  File "C:\Python34\lib\site-packages\django\db\models\query.py", line 240, in __len__
    self._fetch_all()
  File "C:\Python34\lib\site-packages\django\db\models\query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "C:\Python34\lib\site-packages\django\db\models\query.py", line 68, in __iter__
    for row in compiler.results_iter(results):
  File "C:\Python34\lib\site-packages\django\db\models\sql\compiler.py", line 808, in results_iter
    row = self.apply_converters(row, converters)
  File "C:\Python34\lib\site-packages\django\db\models\sql\compiler.py", line 792, in apply_converters
    value = converter(value, expression, self.connection, self.query.context)
  File "C:\Python34\lib\site-packages\sql_server\pyodbc\operations.py", line 106, in convert_datetimefield_value
    value = timezone.make_aware(value, timezone.utc)
  File "C:\Python34\lib\site-packages\django\utils\timezone.py", line 364, in make_aware
    return timezone.localize(value, is_dst=is_dst)
  File "C:\Python34\lib\site-packages\pytz__init__.py", line 226, in localize
    if dt.tzinfo is not None:
AttributeError: 'str' object has no attribute 'tzinfo'
[03/Aug/2016 12:10:53] "GET /admin/ HTTP/1.1" 500 150886

**Comment by michiya** [comment]
Hi @pmahata ,

The issue seems to be almost the same as #15.

The error occurs when you use two different ODBC drivers, an old one that doesn't support `datatime2` type and a new one that supports it.  

I guess you're using `SQL Server` (WDAC ODBC) driver which is bundled with Windows by default and doesn't support `datetime2` type for your application, while your database has been migrated using an another ODBC driver that supports `datetime2` type.

You will be able to resolve the error by installing a modern ODBC driver such as `Microsoft ODBC Driver for SQL Server on Windows` which supports `datetime2` type and using it for your application instead of the legacy WDAC ODBC driver.

I've also made the fix for the error and pushed it to PyPI. So you don't necessarily need to upgrade your ODBC driver to resolve the error if you update django-pyodbc-azure to the latest one. But the fix is just a fallback for legacy ODBC drivers and I strongly recommend that you upgrade your ODBC driver to a newer one for better functionality and performance.

**Comment by michiya** [comment]
Closing the issue because the new version of the package that contains the fix is now available on PyPI. Feel free to open a new issue if you still have a problem.
