### ISSUE TITLE
Error 42000 when switching primary key field with incoming foreign keys

### ISSUE THREAD

**Issue by OskarPersson** [michiya/django-pyodbc-azure#92]
In one of my models I want to switch the primary key from one field to another and delete the old field:

```
class eventType(models.Model):
    - id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    - eventType = models.IntegerField(primary_key=True, default=0)
    + eventType = models.IntegerField(default=0, unique=True)
```

This generates this migration:

```
class Migration(migrations.Migration):

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='id',
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='eventType',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
```

When it gets to the second operation (the `AlterField`) it stops with the following error

```
Running migrations:
  Applying configuration.0004_auto_20170215_1516...Traceback (most recent call last):
  File "manage.py", line 35, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Administrator\Envs\epp\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "C:\Users\Administrator\Envs\epp\lib\site-packages\django\core\management\__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Administrator\Envs\epp\lib\site-packages\django\core\management\base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Administrator\Envs\epp\lib\site-packages\django\core\management\base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Administrator\Envs\epp\lib\site-packages\django\core\management\commands\migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "C:\Users\Administrator\Envs\epp\lib\site-packages\django\db\migrations\executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Administrator\Envs\epp\lib\site-packages\django\db\migrations\executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Administrator\Envs\epp\lib\site-packages\django\db\migrations\executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Users\Administrator\Envs\epp\lib\site-packages\django\db\migrations\migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\Users\Administrator\Envs\epp\lib\site-packages\django\db\migrations\operations\fields.py", line 204, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "C:\Users\Administrator\Envs\epp\lib\site-packages\django\db\backends\base\schema.py", line 495, in alter_field
    old_db_params, new_db_params, strict)
  File "C:\Users\Administrator\Envs\epp\lib\site-packages\sql_server\pyodbc\schema.py", line 318, in _alter_field
    fragment[1],
  File "C:\Users\Administrator\Envs\epp\lib\site-packages\sql_server\pyodbc\schema.py", line 585, in execute
    cursor.execute(sql, params)
  File "C:\Users\Administrator\Envs\epp\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Users\Administrator\Envs\epp\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Administrator\Envs\epp\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Users\Administrator\Envs\epp\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Administrator\Envs\epp\lib\site-packages\sql_server\pyodbc\base.py", line 539, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]The index 'event_event_eventType_id_9db75281_uniq' is dependent on column 'eventType_id'.(5074) (SQLExecDirectW); [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]ALTER TABLE ALTER COLUMN eventType_id failed because one or more objects access this column. (4922)")
```

The model referenced in the error looks like this

```
class event(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    eventType = models.ForeignKey(
        'configuration.EventType',
        on_delete=models.CASCADE
    )
```

---

I am running SQL Server 2016 (version 13.0.4001.0) on Windows Server 2012 R2 Standard

**Comment by OskarPersson** [comment]
Some more information after additional investigation:

The last (and failing) query is `ALTER TABLE [event_event] ALTER COLUMN [eventType_id] int NOT NULL`

I have one migration before and after this failing migration that temporarily disables the `db_constraint` of the  incoming foreign key (needed that in MySQL) while doing the operations in this migration.

**before**:
```
migrations.AlterField(
    model_name='event',
    name='eventType',
    field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='configuration.EventType'),
)

```

**after**
```
migrations.AlterField(
    model_name='event',
    name='eventType',
    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.EventType'),
)
```

Though as noted in the error message the index depending on this field is never deleted, resulting in the query failing.

**Comment by OskarPersson** [comment]
Manually removing this index solves the problem and allows the migration to finish but this should be possible to fix dynamically. The index should probably also be recreated after the operation is done.

**Comment by OskarPersson** [comment]
Tested with both Django 1.10 and Django 1.11 (with respective django-pyodbc-azure versions)

**Comment by michiya** [comment]
The fix is merged into the repo and it is available on PyPI now. Thanks for your contribution!
